# Generated by Django 6.0.4 on 2026-04-29 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('greeting_audio_path', models.CharField(blank=True, help_text='Caminho para o arquivo gerado pelo TTS.', max_length=255, null=True, verbose_name='Caminho do Áudio de Cumprimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Foto de Referência')),
                ('embedding', models.JSONField(blank=True, help_text='Representação matemática do rosto usada para o reconhecimento rápido.', null=True, verbose_name='Embeddings (Vetores do Rosto)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='Endereço MAC')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP Conhecido')),
                ('date_connected', models.DateTimeField(auto_now=True, verbose_name='Última Conexão')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.profile')),
            ],
        ),
    ]
