# Generated by Django 6.0.4 on 2026-05-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_city', models.CharField(default='Rio de Janeiro', max_length=100)),
                ('weather_lat', models.FloatField(default=-22.9064)),
                ('weather_lon', models.FloatField(default=-43.1822)),
                ('news_category', models.CharField(default='geral', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_preference', to='users.profile')),
            ],
        ),
    ]
